CREATE TABLE IF NOT EXISTS "pt_module" (
  "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
  "name" TEXT NOT NULL DEFAULT '',
  "local_path" TEXT NOT NULL DEFAULT '',
  "remote_path" TEXT NOT NULL DEFAULT '',
  "username" TEXT NOT NULL DEFAULT '',
  "password" TEXT NOT NULL DEFAULT '',
  "spec_repo_id" INTEGER NOT NULL DEFAULT 0
);
