CREATE TABLE IF NOT EXISTS "pt_module_repo" (
  "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
  "url" TEXT NOT NULL DEFAULT '',
  "user" TEXT NOT NULL DEFAULT '',
  "pwd" TEXT NOT NULL DEFAULT ''
);

CREATE TABLE IF NOT EXISTS "pt_module" (
  "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
  "name" TEXT NOT NULL DEFAULT '',
  "path" TEXT NOT NULL DEFAULT '',
  "repo_id" INTEGER NOT NULL DEFAULT 0,
  "trunk_id" INTEGER NOT NULL DEFAULT 0,
  "trunk_name" TEXT NOT NULL DEFAULT '',
  "spec_name" TEXT NOT NULL DEFAULT ''
);
